[[redirects]]
from = "/home"
to = "/index.html"
status = 302

[[redirects]]
from = "/home/"
to = "/index.html"
status = 302

[[redirects]]
from = "/home/*"
to = "/index.html"
status = 302

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
