[[redirects]]
from = "/home"
to = "/index.html"
status = 302
force = true 

[[redirects]]
from = "/home/"
to = "/index.html"
status = 302
force = true

[[redirects]]
from = "/home/*"
to = "/index.html"
status = 302
force = true 

[[redirects]]
from = "/widget/*"
to = "/403.html"
status = 403
force = true 


[[redirects]]
from = "/*"
to = "/404.html"
status = 404
